# Generated by Django 5.2.7 on 2025-10-25 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_evento_capacidad_evento_descripcion_evento_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
